
"""
    Chatter API

    Advanced AI Chatbot Backend API Platform

    The version of the OpenAPI document: 0.1.0
    Contact: support@chatter.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chatter_sdk.models.job_create_request import JobCreateRequest

class TestJobCreateRequest(unittest.TestCase):
    """JobCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobCreateRequest:
        """Test JobCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobCreateRequest`
        """
        model = JobCreateRequest()
        if include_optional:
            return JobCreateRequest(
                name = '',
                function_name = '',
                args = [
                    null
                    ],
                kwargs = { },
                priority = 'low',
                max_retries = 0.0,
                schedule_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return JobCreateRequest(
                name = '',
                function_name = '',
        )
        """

    def testJobCreateRequest(self):
        """Test JobCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
