
"""
    Chatter API

    Advanced AI Chatbot Backend API Platform

    The version of the OpenAPI document: 0.1.0
    Contact: support@chatter.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chatter_sdk.models.default_provider import DefaultProvider


class TestDefaultProvider(unittest.TestCase):
    """DefaultProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefaultProvider:
        """Test DefaultProvider
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefaultProvider`
        """
        model = DefaultProvider()
        if include_optional:
            return DefaultProvider(
                model_type = 'llm'
            )
        else:
            return DefaultProvider(
                model_type = 'llm',
        )
        """

    def testDefaultProvider(self):
        """Test DefaultProvider"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == "__main__":
    unittest.main()
