
"""
    Chatter API

    Advanced AI Chatbot Backend API Platform

    The version of the OpenAPI document: 0.1.0
    Contact: support@chatter.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chatter_sdk.models.test_metric import TestMetric


class TestTestMetric(unittest.TestCase):
    """TestMetric unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TestMetric:
        """Test TestMetric
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TestMetric`
        """
        model = TestMetric()
        if include_optional:
            return TestMetric(
                metric_type = 'response_time',
                variant_name = '',
                value = 1.337,
                sample_size = 56,
                confidence_interval = [
                    1.337
                    ]
            )
        else:
            return TestMetric(
                metric_type = 'response_time',
                variant_name = '',
                value = 1.337,
                sample_size = 56,
        )
        """

    def testTestMetric(self):
        """Test TestMetric"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == "__main__":
    unittest.main()
