
"""
    Chatter API

    Advanced AI Chatbot Backend API Platform

    The version of the OpenAPI document: 0.1.0
    Contact: support@chatter.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chatter_sdk.models.plugin_install_request import (
    PluginInstallRequest,
)


class TestPluginInstallRequest(unittest.TestCase):
    """PluginInstallRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PluginInstallRequest:
        """Test PluginInstallRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PluginInstallRequest`
        """
        model = PluginInstallRequest()
        if include_optional:
            return PluginInstallRequest(
                plugin_path = '',
                enable_on_install = True
            )
        else:
            return PluginInstallRequest(
                plugin_path = '',
        )
        """

    def testPluginInstallRequest(self):
        """Test PluginInstallRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == "__main__":
    unittest.main()
