
"""
    Chatter API

    Advanced AI Chatbot Backend API Platform

    The version of the OpenAPI document: 0.1.0
    Contact: support@chatter.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chatter_sdk.api.prompts_api import PromptsApi


class TestPromptsApi(unittest.IsolatedAsyncioTestCase):
    """PromptsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = PromptsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_clone_prompt_api_v1_prompts_prompt_id_clone_post(self) -> None:
        """Test case for clone_prompt_api_v1_prompts_prompt_id_clone_post

        Clone Prompt
        """
        pass

    async def test_create_prompt_api_v1_prompts_post(self) -> None:
        """Test case for create_prompt_api_v1_prompts_post

        Create Prompt
        """
        pass

    async def test_delete_prompt_api_v1_prompts_prompt_id_delete(self) -> None:
        """Test case for delete_prompt_api_v1_prompts_prompt_id_delete

        Delete Prompt
        """
        pass

    async def test_get_prompt_api_v1_prompts_prompt_id_get(self) -> None:
        """Test case for get_prompt_api_v1_prompts_prompt_id_get

        Get Prompt
        """
        pass

    async def test_get_prompt_stats_api_v1_prompts_stats_overview_get(self) -> None:
        """Test case for get_prompt_stats_api_v1_prompts_stats_overview_get

        Get Prompt Stats
        """
        pass

    async def test_list_prompts_api_v1_prompts_get(self) -> None:
        """Test case for list_prompts_api_v1_prompts_get

        List Prompts
        """
        pass

    async def test_test_prompt_api_v1_prompts_prompt_id_test_post(self) -> None:
        """Test case for test_prompt_api_v1_prompts_prompt_id_test_post

        Test Prompt
        """
        pass

    async def test_update_prompt_api_v1_prompts_prompt_id_put(self) -> None:
        """Test case for update_prompt_api_v1_prompts_prompt_id_put

        Update Prompt
        """
        pass


if __name__ == '__main__':
    unittest.main()
