
"""
    Chatter API

    Advanced AI Chatbot Backend API Platform

    The version of the OpenAPI document: 0.1.0
    Contact: support@chatter.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chatter_sdk.models.plugin_list_response import PluginListResponse


class TestPluginListResponse(unittest.TestCase):
    """PluginListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PluginListResponse:
        """Test PluginListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PluginListResponse`
        """
        model = PluginListResponse()
        if include_optional:
            return PluginListResponse(
                plugins = [
                    chatter_sdk.models.plugin_response.PluginResponse(
                        id = '', 
                        name = '', 
                        version = '', 
                        description = '', 
                        author = '', 
                        plugin_type = 'tool', 
                        status = 'installed', 
                        entry_point = '', 
                        capabilities = [
                            { }
                            ], 
                        dependencies = [
                            ''
                            ], 
                        permissions = [
                            ''
                            ], 
                        enabled = True, 
                        error_message = '', 
                        installed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        metadata = { }, )
                    ],
                total = 56
            )
        else:
            return PluginListResponse(
                plugins = [
                    chatter_sdk.models.plugin_response.PluginResponse(
                        id = '', 
                        name = '', 
                        version = '', 
                        description = '', 
                        author = '', 
                        plugin_type = 'tool', 
                        status = 'installed', 
                        entry_point = '', 
                        capabilities = [
                            { }
                            ], 
                        dependencies = [
                            ''
                            ], 
                        permissions = [
                            ''
                            ], 
                        enabled = True, 
                        error_message = '', 
                        installed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        metadata = { }, )
                    ],
                total = 56,
        )
        """

    def testPluginListResponse(self):
        """Test PluginListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == "__main__":
    unittest.main()
