# coding: utf-8

"""
    Chatter API

    Advanced AI Chatbot Backend API Platform

    The version of the OpenAPI document: 0.1.0
    Contact: support@chatter.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chatter_sdk.models.system_analytics_response import SystemAnalyticsResponse

class TestSystemAnalyticsResponse(unittest.TestCase):
    """SystemAnalyticsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SystemAnalyticsResponse:
        """Test SystemAnalyticsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SystemAnalyticsResponse`
        """
        model = SystemAnalyticsResponse()
        if include_optional:
            return SystemAnalyticsResponse(
                total_users = 56,
                active_users_today = 56,
                active_users_week = 56,
                active_users_month = 56,
                system_uptime_seconds = 1.337,
                avg_cpu_usage = 1.337,
                avg_memory_usage = 1.337,
                database_connections = 56,
                total_api_requests = 56,
                requests_per_endpoint = {
                    'key' : 56
                    },
                avg_api_response_time = 1.337,
                api_error_rate = 1.337,
                storage_usage_bytes = 56,
                vector_database_size_bytes = 56,
                cache_hit_rate = 1.337
            )
        else:
            return SystemAnalyticsResponse(
                total_users = 56,
                active_users_today = 56,
                active_users_week = 56,
                active_users_month = 56,
                system_uptime_seconds = 1.337,
                avg_cpu_usage = 1.337,
                avg_memory_usage = 1.337,
                database_connections = 56,
                total_api_requests = 56,
                requests_per_endpoint = {
                    'key' : 56
                    },
                avg_api_response_time = 1.337,
                api_error_rate = 1.337,
                storage_usage_bytes = 56,
                vector_database_size_bytes = 56,
                cache_hit_rate = 1.337,
        )
        """

    def testSystemAnalyticsResponse(self):
        """Test SystemAnalyticsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
