# coding: utf-8

"""
    Chatter API

    Advanced AI Chatbot Backend API Platform

    The version of the OpenAPI document: 0.1.0
    Contact: support@chatter.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chatter_sdk.models.ab_test_action_response import ABTestActionResponse

class TestABTestActionResponse(unittest.TestCase):
    """ABTestActionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ABTestActionResponse:
        """Test ABTestActionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ABTestActionResponse`
        """
        model = ABTestActionResponse()
        if include_optional:
            return ABTestActionResponse(
                success = True,
                message = '',
                test_id = '',
                new_status = 'draft'
            )
        else:
            return ABTestActionResponse(
                success = True,
                message = '',
                test_id = '',
                new_status = 'draft',
        )
        """

    def testABTestActionResponse(self):
        """Test ABTestActionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
