# coding: utf-8

"""
    Chatter API

    Advanced AI Chatbot Backend API Platform

    The version of the OpenAPI document: 0.1.0
    Contact: support@chatter.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chatter_sdk.models.tool_permission_update import ToolPermissionUpdate

class TestToolPermissionUpdate(unittest.TestCase):
    """ToolPermissionUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ToolPermissionUpdate:
        """Test ToolPermissionUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ToolPermissionUpdate`
        """
        model = ToolPermissionUpdate()
        if include_optional:
            return ToolPermissionUpdate(
                access_level = 'none',
                rate_limit_per_hour = 0.0,
                rate_limit_per_day = 0.0,
                allowed_hours = [
                    56
                    ],
                allowed_days = [
                    56
                    ],
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ToolPermissionUpdate(
        )
        """

    def testToolPermissionUpdate(self):
        """Test ToolPermissionUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
