# Pre-commit hooks for the Chatter project
# Run 'pre-commit install' to enable these hooks
# Run 'pre-commit run --all-files' to run hooks on all files

repos:
  # Backend Python hooks
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.12
        args: [--line-length=72]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=72]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [-r, chatter, -x, tests]

  # Frontend TypeScript/React hooks
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.35.0
    hooks:
      - id: eslint
        files: \.(ts|tsx|js|jsx)$
        types: [file]
        args: [--fix]
        additional_dependencies:
          - '@eslint/js@^9.35.0'
          - '@typescript-eslint/eslint-plugin@^8.41.0'
          - '@typescript-eslint/parser@^8.41.0'
          - 'eslint-plugin-react@^7.37.5'
          - 'eslint-plugin-react-hooks@^5.2.0'
          - 'globals@^16.4.0'
          - 'typescript-eslint@^8.43.0'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.4.2
    hooks:
      - id: prettier
        files: \.(ts|tsx|js|jsx|json|css|scss|md)$

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: detect-private-key

  # Security scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
        exclude: package.lock.json

  # Commit message formatting
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]