/* tslint:disable */
/* eslint-disable */
/**
 * Chatter API
 * Advanced AI Chatbot Backend API Platform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for API key creation.
 * @export
 * @interface APIKeyCreate
 */
export interface APIKeyCreate {
    /**
     * API key name
     * @type {string}
     * @memberof APIKeyCreate
     */
    name: string;
}

/**
 * Check if a given object implements the APIKeyCreate interface.
 */
export function instanceOfAPIKeyCreate(value: object): value is APIKeyCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function APIKeyCreateFromJSON(json: any): APIKeyCreate {
    return APIKeyCreateFromJSONTyped(json, false);
}

export function APIKeyCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIKeyCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function APIKeyCreateToJSON(json: any): APIKeyCreate {
    return APIKeyCreateToJSONTyped(json, false);
}

export function APIKeyCreateToJSONTyped(value?: APIKeyCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

