/* tslint:disable */
/* eslint-disable */
/**
 * Chatter API
 * Advanced AI Chatbot Backend API Platform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for API key response.
 * @export
 * @interface APIKeyResponse
 */
export interface APIKeyResponse {
    /**
     * User ID
     * @type {string}
     * @memberof APIKeyResponse
     */
    id: string;
    /**
     * API key
     * @type {string}
     * @memberof APIKeyResponse
     */
    apiKey: string;
    /**
     * API key name
     * @type {string}
     * @memberof APIKeyResponse
     */
    apiKeyName: string;
}

/**
 * Check if a given object implements the APIKeyResponse interface.
 */
export function instanceOfAPIKeyResponse(value: object): value is APIKeyResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('apiKey' in value) || value['apiKey'] === undefined) return false;
    if (!('apiKeyName' in value) || value['apiKeyName'] === undefined) return false;
    return true;
}

export function APIKeyResponseFromJSON(json: any): APIKeyResponse {
    return APIKeyResponseFromJSONTyped(json, false);
}

export function APIKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'apiKey': json['api_key'],
        'apiKeyName': json['api_key_name'],
    };
}

export function APIKeyResponseToJSON(json: any): APIKeyResponse {
    return APIKeyResponseToJSONTyped(json, false);
}

export function APIKeyResponseToJSONTyped(value?: APIKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'api_key': value['apiKey'],
        'api_key_name': value['apiKeyName'],
    };
}

