/* tslint:disable */
/* eslint-disable */
/**
 * Chatter API
 * Advanced AI Chatbot Backend API Platform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PerformanceMetricsResponse } from './PerformanceMetricsResponse';
import {
    PerformanceMetricsResponseFromJSON,
    PerformanceMetricsResponseFromJSONTyped,
    PerformanceMetricsResponseToJSON,
    PerformanceMetricsResponseToJSONTyped,
} from './PerformanceMetricsResponse';
import type { SystemAnalyticsResponse } from './SystemAnalyticsResponse';
import {
    SystemAnalyticsResponseFromJSON,
    SystemAnalyticsResponseFromJSONTyped,
    SystemAnalyticsResponseToJSON,
    SystemAnalyticsResponseToJSONTyped,
} from './SystemAnalyticsResponse';
import type { DocumentAnalyticsResponse } from './DocumentAnalyticsResponse';
import {
    DocumentAnalyticsResponseFromJSON,
    DocumentAnalyticsResponseFromJSONTyped,
    DocumentAnalyticsResponseToJSON,
    DocumentAnalyticsResponseToJSONTyped,
} from './DocumentAnalyticsResponse';
import type { ConversationStatsResponse } from './ConversationStatsResponse';
import {
    ConversationStatsResponseFromJSON,
    ConversationStatsResponseFromJSONTyped,
    ConversationStatsResponseToJSON,
    ConversationStatsResponseToJSONTyped,
} from './ConversationStatsResponse';
import type { UsageMetricsResponse } from './UsageMetricsResponse';
import {
    UsageMetricsResponseFromJSON,
    UsageMetricsResponseFromJSONTyped,
    UsageMetricsResponseToJSON,
    UsageMetricsResponseToJSONTyped,
} from './UsageMetricsResponse';

/**
 * Schema for analytics dashboard response.
 * @export
 * @interface DashboardResponse
 */
export interface DashboardResponse {
    /**
     * 
     * @type {ConversationStatsResponse}
     * @memberof DashboardResponse
     */
    conversationStats: ConversationStatsResponse;
    /**
     * 
     * @type {UsageMetricsResponse}
     * @memberof DashboardResponse
     */
    usageMetrics: UsageMetricsResponse;
    /**
     * 
     * @type {PerformanceMetricsResponse}
     * @memberof DashboardResponse
     */
    performanceMetrics: PerformanceMetricsResponse;
    /**
     * 
     * @type {DocumentAnalyticsResponse}
     * @memberof DashboardResponse
     */
    documentAnalytics: DocumentAnalyticsResponse;
    /**
     * 
     * @type {SystemAnalyticsResponse}
     * @memberof DashboardResponse
     */
    systemHealth: SystemAnalyticsResponse;
    /**
     * Custom metrics
     * @type {Array<{ [key: string]: any; }>}
     * @memberof DashboardResponse
     */
    customMetrics: Array<{ [key: string]: any; }>;
    /**
     * Dashboard generation time
     * @type {Date}
     * @memberof DashboardResponse
     */
    generatedAt: Date;
}

/**
 * Check if a given object implements the DashboardResponse interface.
 */
export function instanceOfDashboardResponse(value: object): value is DashboardResponse {
    if (!('conversationStats' in value) || value['conversationStats'] === undefined) return false;
    if (!('usageMetrics' in value) || value['usageMetrics'] === undefined) return false;
    if (!('performanceMetrics' in value) || value['performanceMetrics'] === undefined) return false;
    if (!('documentAnalytics' in value) || value['documentAnalytics'] === undefined) return false;
    if (!('systemHealth' in value) || value['systemHealth'] === undefined) return false;
    if (!('customMetrics' in value) || value['customMetrics'] === undefined) return false;
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    return true;
}

export function DashboardResponseFromJSON(json: any): DashboardResponse {
    return DashboardResponseFromJSONTyped(json, false);
}

export function DashboardResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'conversationStats': ConversationStatsResponseFromJSON(json['conversation_stats']),
        'usageMetrics': UsageMetricsResponseFromJSON(json['usage_metrics']),
        'performanceMetrics': PerformanceMetricsResponseFromJSON(json['performance_metrics']),
        'documentAnalytics': DocumentAnalyticsResponseFromJSON(json['document_analytics']),
        'systemHealth': SystemAnalyticsResponseFromJSON(json['system_health']),
        'customMetrics': json['custom_metrics'],
        'generatedAt': (new Date(json['generated_at'])),
    };
}

export function DashboardResponseToJSON(json: any): DashboardResponse {
    return DashboardResponseToJSONTyped(json, false);
}

export function DashboardResponseToJSONTyped(value?: DashboardResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversation_stats': ConversationStatsResponseToJSON(value['conversationStats']),
        'usage_metrics': UsageMetricsResponseToJSON(value['usageMetrics']),
        'performance_metrics': PerformanceMetricsResponseToJSON(value['performanceMetrics']),
        'document_analytics': DocumentAnalyticsResponseToJSON(value['documentAnalytics']),
        'system_health': SystemAnalyticsResponseToJSON(value['systemHealth']),
        'custom_metrics': value['customMetrics'],
        'generated_at': ((value['generatedAt']).toISOString()),
    };
}

