/* tslint:disable */
/* eslint-disable */
/**
 * Chatter API
 * Advanced AI Chatbot Backend API Platform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response schema for job actions.
 * @export
 * @interface JobActionResponse
 */
export interface JobActionResponse {
    /**
     * Whether action was successful
     * @type {boolean}
     * @memberof JobActionResponse
     */
    success: boolean;
    /**
     * Action result message
     * @type {string}
     * @memberof JobActionResponse
     */
    message: string;
    /**
     * Job ID
     * @type {string}
     * @memberof JobActionResponse
     */
    jobId: string;
}

/**
 * Check if a given object implements the JobActionResponse interface.
 */
export function instanceOfJobActionResponse(value: object): value is JobActionResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    return true;
}

export function JobActionResponseFromJSON(json: any): JobActionResponse {
    return JobActionResponseFromJSONTyped(json, false);
}

export function JobActionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobActionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
        'jobId': json['job_id'],
    };
}

export function JobActionResponseToJSON(json: any): JobActionResponse {
    return JobActionResponseToJSONTyped(json, false);
}

export function JobActionResponseToJSONTyped(value?: JobActionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'job_id': value['jobId'],
    };
}

