/* tslint:disable */
/* eslint-disable */
/**
 * Chatter API
 * Advanced AI Chatbot Backend API Platform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for password reset confirmation response.
 * @export
 * @interface PasswordResetConfirmResponse
 */
export interface PasswordResetConfirmResponse {
    /**
     * Success message
     * @type {string}
     * @memberof PasswordResetConfirmResponse
     */
    message: string;
}

/**
 * Check if a given object implements the PasswordResetConfirmResponse interface.
 */
export function instanceOfPasswordResetConfirmResponse(value: object): value is PasswordResetConfirmResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PasswordResetConfirmResponseFromJSON(json: any): PasswordResetConfirmResponse {
    return PasswordResetConfirmResponseFromJSONTyped(json, false);
}

export function PasswordResetConfirmResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetConfirmResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function PasswordResetConfirmResponseToJSON(json: any): PasswordResetConfirmResponse {
    return PasswordResetConfirmResponseToJSONTyped(json, false);
}

export function PasswordResetConfirmResponseToJSONTyped(value?: PasswordResetConfirmResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

