/* tslint:disable */
/* eslint-disable */
/**
 * Chatter API
 * Advanced AI Chatbot Backend API Platform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProfileType } from './ProfileType';
import {
    ProfileTypeFromJSON,
    ProfileTypeFromJSONTyped,
    ProfileTypeToJSON,
    ProfileTypeToJSONTyped,
} from './ProfileType';

/**
 * Schema for creating a profile.
 * @export
 * @interface ProfileCreate
 */
export interface ProfileCreate {
    /**
     * Profile name
     * @type {string}
     * @memberof ProfileCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileCreate
     */
    description?: string | null;
    /**
     * 
     * @type {ProfileType}
     * @memberof ProfileCreate
     */
    profileType?: ProfileType;
    /**
     * LLM provider (openai, anthropic, etc.)
     * @type {string}
     * @memberof ProfileCreate
     */
    llmProvider: string;
    /**
     * LLM model name
     * @type {string}
     * @memberof ProfileCreate
     */
    llmModel: string;
    /**
     * Temperature for generation
     * @type {number}
     * @memberof ProfileCreate
     */
    temperature?: number;
    /**
     * 
     * @type {number}
     * @memberof ProfileCreate
     */
    topP?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProfileCreate
     */
    topK?: number | null;
    /**
     * Maximum tokens to generate
     * @type {number}
     * @memberof ProfileCreate
     */
    maxTokens?: number;
    /**
     * 
     * @type {number}
     * @memberof ProfileCreate
     */
    presencePenalty?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProfileCreate
     */
    frequencyPenalty?: number | null;
    /**
     * Context window size
     * @type {number}
     * @memberof ProfileCreate
     */
    contextWindow?: number;
    /**
     * 
     * @type {string}
     * @memberof ProfileCreate
     */
    systemPrompt?: string | null;
    /**
     * Enable conversation memory
     * @type {boolean}
     * @memberof ProfileCreate
     */
    memoryEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProfileCreate
     */
    memoryStrategy?: string | null;
    /**
     * Enable document retrieval
     * @type {boolean}
     * @memberof ProfileCreate
     */
    enableRetrieval?: boolean;
    /**
     * Number of documents to retrieve
     * @type {number}
     * @memberof ProfileCreate
     */
    retrievalLimit?: number;
    /**
     * Minimum retrieval score
     * @type {number}
     * @memberof ProfileCreate
     */
    retrievalScoreThreshold?: number;
    /**
     * Enable tool calling
     * @type {boolean}
     * @memberof ProfileCreate
     */
    enableTools?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProfileCreate
     */
    availableTools?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileCreate
     */
    toolChoice?: string | null;
    /**
     * Enable content filtering
     * @type {boolean}
     * @memberof ProfileCreate
     */
    contentFilterEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProfileCreate
     */
    safetyLevel?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileCreate
     */
    responseFormat?: string | null;
    /**
     * Enable streaming responses
     * @type {boolean}
     * @memberof ProfileCreate
     */
    streamResponse?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ProfileCreate
     */
    seed?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProfileCreate
     */
    stopSequences?: Array<string> | null;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof ProfileCreate
     */
    logitBias?: { [key: string]: number; } | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileCreate
     */
    embeddingProvider?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileCreate
     */
    embeddingModel?: string | null;
    /**
     * Whether profile is public
     * @type {boolean}
     * @memberof ProfileCreate
     */
    isPublic?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProfileCreate
     */
    tags?: Array<string> | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ProfileCreate
     */
    extraMetadata?: { [key: string]: any; } | null;
}



/**
 * Check if a given object implements the ProfileCreate interface.
 */
export function instanceOfProfileCreate(value: object): value is ProfileCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('llmProvider' in value) || value['llmProvider'] === undefined) return false;
    if (!('llmModel' in value) || value['llmModel'] === undefined) return false;
    return true;
}

export function ProfileCreateFromJSON(json: any): ProfileCreate {
    return ProfileCreateFromJSONTyped(json, false);
}

export function ProfileCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'profileType': json['profile_type'] == null ? undefined : ProfileTypeFromJSON(json['profile_type']),
        'llmProvider': json['llm_provider'],
        'llmModel': json['llm_model'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'topP': json['top_p'] == null ? undefined : json['top_p'],
        'topK': json['top_k'] == null ? undefined : json['top_k'],
        'maxTokens': json['max_tokens'] == null ? undefined : json['max_tokens'],
        'presencePenalty': json['presence_penalty'] == null ? undefined : json['presence_penalty'],
        'frequencyPenalty': json['frequency_penalty'] == null ? undefined : json['frequency_penalty'],
        'contextWindow': json['context_window'] == null ? undefined : json['context_window'],
        'systemPrompt': json['system_prompt'] == null ? undefined : json['system_prompt'],
        'memoryEnabled': json['memory_enabled'] == null ? undefined : json['memory_enabled'],
        'memoryStrategy': json['memory_strategy'] == null ? undefined : json['memory_strategy'],
        'enableRetrieval': json['enable_retrieval'] == null ? undefined : json['enable_retrieval'],
        'retrievalLimit': json['retrieval_limit'] == null ? undefined : json['retrieval_limit'],
        'retrievalScoreThreshold': json['retrieval_score_threshold'] == null ? undefined : json['retrieval_score_threshold'],
        'enableTools': json['enable_tools'] == null ? undefined : json['enable_tools'],
        'availableTools': json['available_tools'] == null ? undefined : json['available_tools'],
        'toolChoice': json['tool_choice'] == null ? undefined : json['tool_choice'],
        'contentFilterEnabled': json['content_filter_enabled'] == null ? undefined : json['content_filter_enabled'],
        'safetyLevel': json['safety_level'] == null ? undefined : json['safety_level'],
        'responseFormat': json['response_format'] == null ? undefined : json['response_format'],
        'streamResponse': json['stream_response'] == null ? undefined : json['stream_response'],
        'seed': json['seed'] == null ? undefined : json['seed'],
        'stopSequences': json['stop_sequences'] == null ? undefined : json['stop_sequences'],
        'logitBias': json['logit_bias'] == null ? undefined : json['logit_bias'],
        'embeddingProvider': json['embedding_provider'] == null ? undefined : json['embedding_provider'],
        'embeddingModel': json['embedding_model'] == null ? undefined : json['embedding_model'],
        'isPublic': json['is_public'] == null ? undefined : json['is_public'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'extraMetadata': json['extra_metadata'] == null ? undefined : json['extra_metadata'],
    };
}

export function ProfileCreateToJSON(json: any): ProfileCreate {
    return ProfileCreateToJSONTyped(json, false);
}

export function ProfileCreateToJSONTyped(value?: ProfileCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'profile_type': ProfileTypeToJSON(value['profileType']),
        'llm_provider': value['llmProvider'],
        'llm_model': value['llmModel'],
        'temperature': value['temperature'],
        'top_p': value['topP'],
        'top_k': value['topK'],
        'max_tokens': value['maxTokens'],
        'presence_penalty': value['presencePenalty'],
        'frequency_penalty': value['frequencyPenalty'],
        'context_window': value['contextWindow'],
        'system_prompt': value['systemPrompt'],
        'memory_enabled': value['memoryEnabled'],
        'memory_strategy': value['memoryStrategy'],
        'enable_retrieval': value['enableRetrieval'],
        'retrieval_limit': value['retrievalLimit'],
        'retrieval_score_threshold': value['retrievalScoreThreshold'],
        'enable_tools': value['enableTools'],
        'available_tools': value['availableTools'],
        'tool_choice': value['toolChoice'],
        'content_filter_enabled': value['contentFilterEnabled'],
        'safety_level': value['safetyLevel'],
        'response_format': value['responseFormat'],
        'stream_response': value['streamResponse'],
        'seed': value['seed'],
        'stop_sequences': value['stopSequences'],
        'logit_bias': value['logitBias'],
        'embedding_provider': value['embeddingProvider'],
        'embedding_model': value['embeddingModel'],
        'is_public': value['isPublic'],
        'tags': value['tags'],
        'extra_metadata': value['extraMetadata'],
    };
}

