/* tslint:disable */
/* eslint-disable */
/**
 * Chatter API
 * Advanced AI Chatbot Backend API Platform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Test variant definition.
 * @export
 * @interface TestVariant
 */
export interface TestVariant {
    /**
     * Variant name
     * @type {string}
     * @memberof TestVariant
     */
    name: string;
    /**
     * Variant description
     * @type {string}
     * @memberof TestVariant
     */
    description: string;
    /**
     * Variant configuration
     * @type {{ [key: string]: any; }}
     * @memberof TestVariant
     */
    _configuration: { [key: string]: any; };
    /**
     * Variant weight for allocation
     * @type {number}
     * @memberof TestVariant
     */
    weight?: number;
}

/**
 * Check if a given object implements the TestVariant interface.
 */
export function instanceOfTestVariant(value: object): value is TestVariant {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('_configuration' in value) || value['_configuration'] === undefined) return false;
    return true;
}

export function TestVariantFromJSON(json: any): TestVariant {
    return TestVariantFromJSONTyped(json, false);
}

export function TestVariantFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestVariant {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        '_configuration': json['configuration'],
        'weight': json['weight'] == null ? undefined : json['weight'],
    };
}

export function TestVariantToJSON(json: any): TestVariant {
    return TestVariantToJSONTyped(json, false);
}

export function TestVariantToJSONTyped(value?: TestVariant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'configuration': value['_configuration'],
        'weight': value['weight'],
    };
}

