/* tslint:disable */
/* eslint-disable */
/**
 * Chatter API
 * Advanced AI Chatbot Backend API Platform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for tool server delete response.
 * @export
 * @interface ToolServerDeleteResponse
 */
export interface ToolServerDeleteResponse {
    /**
     * Success message
     * @type {string}
     * @memberof ToolServerDeleteResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ToolServerDeleteResponse interface.
 */
export function instanceOfToolServerDeleteResponse(value: object): value is ToolServerDeleteResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ToolServerDeleteResponseFromJSON(json: any): ToolServerDeleteResponse {
    return ToolServerDeleteResponseFromJSONTyped(json, false);
}

export function ToolServerDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolServerDeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ToolServerDeleteResponseToJSON(json: any): ToolServerDeleteResponse {
    return ToolServerDeleteResponseToJSONTyped(json, false);
}

export function ToolServerDeleteResponseToJSONTyped(value?: ToolServerDeleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

