/* tslint:disable */
/* eslint-disable */
/**
 * Chatter API
 * Advanced AI Chatbot Backend API Platform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowTemplateInfo } from './WorkflowTemplateInfo';
import {
    WorkflowTemplateInfoFromJSON,
    WorkflowTemplateInfoFromJSONTyped,
    WorkflowTemplateInfoToJSON,
    WorkflowTemplateInfoToJSONTyped,
} from './WorkflowTemplateInfo';

/**
 * Schema for workflow templates response.
 * @export
 * @interface WorkflowTemplatesResponse
 */
export interface WorkflowTemplatesResponse {
    /**
     * Available templates
     * @type {{ [key: string]: WorkflowTemplateInfo; }}
     * @memberof WorkflowTemplatesResponse
     */
    templates: { [key: string]: WorkflowTemplateInfo; };
    /**
     * Total number of templates
     * @type {number}
     * @memberof WorkflowTemplatesResponse
     */
    totalCount: number;
}

/**
 * Check if a given object implements the WorkflowTemplatesResponse interface.
 */
export function instanceOfWorkflowTemplatesResponse(value: object): value is WorkflowTemplatesResponse {
    if (!('templates' in value) || value['templates'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    return true;
}

export function WorkflowTemplatesResponseFromJSON(json: any): WorkflowTemplatesResponse {
    return WorkflowTemplatesResponseFromJSONTyped(json, false);
}

export function WorkflowTemplatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowTemplatesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'templates': (mapValues(json['templates'], WorkflowTemplateInfoFromJSON)),
        'totalCount': json['total_count'],
    };
}

export function WorkflowTemplatesResponseToJSON(json: any): WorkflowTemplatesResponse {
    return WorkflowTemplatesResponseToJSONTyped(json, false);
}

export function WorkflowTemplatesResponseToJSONTyped(value?: WorkflowTemplatesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'templates': (mapValues(value['templates'], WorkflowTemplateInfoToJSON)),
        'total_count': value['totalCount'],
    };
}

