/* tslint:disable */
/* eslint-disable */
/**
 * Chatter API
 * Advanced AI Chatbot Backend API Platform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for creating a workflow template.
 * @export
 * @interface WorkflowTemplateCreate
 */
export interface WorkflowTemplateCreate {
    /**
     * Template name
     * @type {string}
     * @memberof WorkflowTemplateCreate
     */
    name: string;
    /**
     * Template description
     * @type {string}
     * @memberof WorkflowTemplateCreate
     */
    description: string;
    /**
     * Workflow type
     * @type {string}
     * @memberof WorkflowTemplateCreate
     */
    workflowType: string;
    /**
     * Template category
     * @type {string}
     * @memberof WorkflowTemplateCreate
     */
    category?: string;
    /**
     * Default parameters
     * @type {{ [key: string]: any; }}
     * @memberof WorkflowTemplateCreate
     */
    defaultParams?: { [key: string]: any; };
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkflowTemplateCreate
     */
    requiredTools?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkflowTemplateCreate
     */
    requiredRetrievers?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkflowTemplateCreate
     */
    tags?: Array<string> | null;
    /**
     * Whether template is public
     * @type {boolean}
     * @memberof WorkflowTemplateCreate
     */
    isPublic?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WorkflowTemplateCreate
     */
    workflowDefinitionId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WorkflowTemplateCreate
     */
    baseTemplateId?: string | null;
}

/**
 * Check if a given object implements the WorkflowTemplateCreate interface.
 */
export function instanceOfWorkflowTemplateCreate(value: object): value is WorkflowTemplateCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('workflowType' in value) || value['workflowType'] === undefined) return false;
    return true;
}

export function WorkflowTemplateCreateFromJSON(json: any): WorkflowTemplateCreate {
    return WorkflowTemplateCreateFromJSONTyped(json, false);
}

export function WorkflowTemplateCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowTemplateCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'workflowType': json['workflow_type'],
        'category': json['category'] == null ? undefined : json['category'],
        'defaultParams': json['default_params'] == null ? undefined : json['default_params'],
        'requiredTools': json['required_tools'] == null ? undefined : json['required_tools'],
        'requiredRetrievers': json['required_retrievers'] == null ? undefined : json['required_retrievers'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'isPublic': json['is_public'] == null ? undefined : json['is_public'],
        'workflowDefinitionId': json['workflow_definition_id'] == null ? undefined : json['workflow_definition_id'],
        'baseTemplateId': json['base_template_id'] == null ? undefined : json['base_template_id'],
    };
}

export function WorkflowTemplateCreateToJSON(json: any): WorkflowTemplateCreate {
    return WorkflowTemplateCreateToJSONTyped(json, false);
}

export function WorkflowTemplateCreateToJSONTyped(value?: WorkflowTemplateCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'workflow_type': value['workflowType'],
        'category': value['category'],
        'default_params': value['defaultParams'],
        'required_tools': value['requiredTools'],
        'required_retrievers': value['requiredRetrievers'],
        'tags': value['tags'],
        'is_public': value['isPublic'],
        'workflow_definition_id': value['workflowDefinitionId'],
        'base_template_id': value['baseTemplateId'],
    };
}

