/* tslint:disable */
/* eslint-disable */
/**
 * Chatter API
 * Advanced AI Chatbot Backend API Platform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Types of backups.
 * @export
 */
export const BackupType = {
    full: 'full',
    incremental: 'incremental',
    differential: 'differential'
} as const;
export type BackupType = typeof BackupType[keyof typeof BackupType];


export function instanceOfBackupType(value: any): boolean {
    for (const key in BackupType) {
        if (Object.prototype.hasOwnProperty.call(BackupType, key)) {
            if (BackupType[key as keyof typeof BackupType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BackupTypeFromJSON(json: any): BackupType {
    return BackupTypeFromJSONTyped(json, false);
}

export function BackupTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackupType {
    return json as BackupType;
}

export function BackupTypeToJSON(value?: BackupType | null): any {
    return value as any;
}

export function BackupTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): BackupType {
    return value as BackupType;
}

