/* tslint:disable */
/* eslint-disable */
/**
 * Chatter API
 * Advanced AI Chatbot Backend API Platform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SortingRequest } from './SortingRequest';
import {
    SortingRequestFromJSON,
    SortingRequestFromJSONTyped,
    SortingRequestToJSON,
    SortingRequestToJSONTyped,
} from './SortingRequest';
import type { PaginationRequest } from './PaginationRequest';
import {
    PaginationRequestFromJSON,
    PaginationRequestFromJSONTyped,
    PaginationRequestToJSON,
    PaginationRequestToJSONTyped,
} from './PaginationRequest';

/**
 * 
 * @export
 * @interface BodyListAgentsApiV1AgentsGet
 */
export interface BodyListAgentsApiV1AgentsGet {
    /**
     * 
     * @type {PaginationRequest}
     * @memberof BodyListAgentsApiV1AgentsGet
     */
    pagination?: PaginationRequest;
    /**
     * 
     * @type {SortingRequest}
     * @memberof BodyListAgentsApiV1AgentsGet
     */
    sorting?: SortingRequest;
    /**
     * 
     * @type {Array<string>}
     * @memberof BodyListAgentsApiV1AgentsGet
     */
    tags?: Array<string> | null;
}

/**
 * Check if a given object implements the BodyListAgentsApiV1AgentsGet interface.
 */
export function instanceOfBodyListAgentsApiV1AgentsGet(value: object): value is BodyListAgentsApiV1AgentsGet {
    return true;
}

export function BodyListAgentsApiV1AgentsGetFromJSON(json: any): BodyListAgentsApiV1AgentsGet {
    return BodyListAgentsApiV1AgentsGetFromJSONTyped(json, false);
}

export function BodyListAgentsApiV1AgentsGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyListAgentsApiV1AgentsGet {
    if (json == null) {
        return json;
    }
    return {
        
        'pagination': json['pagination'] == null ? undefined : PaginationRequestFromJSON(json['pagination']),
        'sorting': json['sorting'] == null ? undefined : SortingRequestFromJSON(json['sorting']),
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function BodyListAgentsApiV1AgentsGetToJSON(json: any): BodyListAgentsApiV1AgentsGet {
    return BodyListAgentsApiV1AgentsGetToJSONTyped(json, false);
}

export function BodyListAgentsApiV1AgentsGetToJSONTyped(value?: BodyListAgentsApiV1AgentsGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pagination': PaginationRequestToJSON(value['pagination']),
        'sorting': SortingRequestToJSON(value['sorting']),
        'tags': value['tags'],
    };
}

