/* tslint:disable */
/* eslint-disable */
/**
 * Chatter API
 * Advanced AI Chatbot Backend API Platform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Maximum value for numeric types
 * @export
 * @interface MaxValue
 */
export interface MaxValue {
}

/**
 * Check if a given object implements the MaxValue interface.
 */
export function instanceOfMaxValue(value: object): value is MaxValue {
    return true;
}

export function MaxValueFromJSON(json: any): MaxValue {
    return MaxValueFromJSONTyped(json, false);
}

export function MaxValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaxValue {
    return json;
}

export function MaxValueToJSON(json: any): MaxValue {
    return MaxValueToJSONTyped(json, false);
}

export function MaxValueToJSONTyped(value?: MaxValue | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

