/* tslint:disable */
/* eslint-disable */
/**
 * Chatter API
 * Advanced AI Chatbot Backend API Platform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response schema for plugin deletion.
 * @export
 * @interface PluginDeleteResponse
 */
export interface PluginDeleteResponse {
    /**
     * Whether deletion was successful
     * @type {boolean}
     * @memberof PluginDeleteResponse
     */
    success: boolean;
    /**
     * Deletion result message
     * @type {string}
     * @memberof PluginDeleteResponse
     */
    message: string;
}

/**
 * Check if a given object implements the PluginDeleteResponse interface.
 */
export function instanceOfPluginDeleteResponse(value: object): value is PluginDeleteResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PluginDeleteResponseFromJSON(json: any): PluginDeleteResponse {
    return PluginDeleteResponseFromJSONTyped(json, false);
}

export function PluginDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginDeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
    };
}

export function PluginDeleteResponseToJSON(json: any): PluginDeleteResponse {
    return PluginDeleteResponseToJSONTyped(json, false);
}

export function PluginDeleteResponseToJSONTyped(value?: PluginDeleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
    };
}

