/* tslint:disable */
/* eslint-disable */
/**
 * Chatter API
 * Advanced AI Chatbot Backend API Platform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for profile delete response.
 * @export
 * @interface ProfileDeleteResponse
 */
export interface ProfileDeleteResponse {
    /**
     * Success message
     * @type {string}
     * @memberof ProfileDeleteResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ProfileDeleteResponse interface.
 */
export function instanceOfProfileDeleteResponse(value: object): value is ProfileDeleteResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ProfileDeleteResponseFromJSON(json: any): ProfileDeleteResponse {
    return ProfileDeleteResponseFromJSONTyped(json, false);
}

export function ProfileDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileDeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ProfileDeleteResponseToJSON(json: any): ProfileDeleteResponse {
    return ProfileDeleteResponseToJSONTyped(json, false);
}

export function ProfileDeleteResponseToJSONTyped(value?: ProfileDeleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

