/* tslint:disable */
/* eslint-disable */
/**
 * Chatter API
 * Advanced AI Chatbot Backend API Platform
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for user login.
 * @export
 * @interface UserLogin
 */
export interface UserLogin {
    /**
     * 
     * @type {string}
     * @memberof UserLogin
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserLogin
     */
    username?: string | null;
    /**
     * Password
     * @type {string}
     * @memberof UserLogin
     */
    password: string;
    /**
     * Remember login
     * @type {boolean}
     * @memberof UserLogin
     */
    rememberMe?: boolean;
}

/**
 * Check if a given object implements the UserLogin interface.
 */
export function instanceOfUserLogin(value: object): value is UserLogin {
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UserLoginFromJSON(json: any): UserLogin {
    return UserLoginFromJSONTyped(json, false);
}

export function UserLoginFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLogin {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'],
        'rememberMe': json['remember_me'] == null ? undefined : json['remember_me'],
    };
}

export function UserLoginToJSON(json: any): UserLogin {
    return UserLoginToJSONTyped(json, false);
}

export function UserLoginToJSONTyped(value?: UserLogin | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'username': value['username'],
        'password': value['password'],
        'remember_me': value['rememberMe'],
    };
}

