"""Pydantic schemas for API request/response models."""

# Star imports are intentional for convenience re-export of all schemas
from chatter.schemas.analytics import *  # noqa: F403
from chatter.schemas.auth import *  # noqa: F403
from chatter.schemas.chat import *  # noqa: F403
from chatter.schemas.common import *  # noqa: F403
from chatter.schemas.document import *  # noqa: F403
from chatter.schemas.events import *  # noqa: F403
from chatter.schemas.health import *  # noqa: F403
from chatter.schemas.model_registry import *  # noqa: F403
from chatter.schemas.profile import *  # noqa: F403
from chatter.schemas.prompt import *  # noqa: F403
from chatter.schemas.toolserver import *  # noqa: F403
from chatter.schemas.utilities import *  # noqa: F403

__all__ = [
    # Common schemas
    "PaginationRequest",
    "SortingRequest",
    "PaginatedRequest",
    "ListRequestBase",
    "GetRequestBase",
    "DeleteRequestBase",
    # Auth schemas
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserLogin",
    "TokenResponse",
    "TokenRefresh",
    "PasswordChange",
    "PasswordReset",
    "PasswordResetConfirm",
    "EmailVerification",
    "APIKeyCreate",
    "APIKeyResponse",
    "TokenRefreshResponse",
    "PasswordChangeResponse",
    "APIKeyRevokeResponse",
    "AccountDeactivateResponse",
    # Chat schemas
    "MessageBase",
    "MessageCreate",
    "MessageResponse",
    "ConversationBase",
    "ConversationCreate",
    "ConversationUpdate",
    "ConversationResponse",
    "ConversationWithMessages",
    "ChatRequest",
    "ChatResponse",
    "StreamingChatChunk",
    "ConversationListRequest",
    "ConversationListResponse",
    "ConversationGetRequest",
    "ConversationDeleteRequest",
    "ConversationMessagesRequest",
    "AvailableToolsRequest",
    "McpStatusRequest",
    "ConversationDeleteResponse",
    "MessageDeleteResponse",
    "AvailableToolResponse",
    "AvailableToolsResponse",
    "McpStatusResponse",
    # Document schemas
    "DocumentBase",
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentResponse",
    "DocumentSearchRequest",
    "DocumentSearchResult",
    "DocumentSearchResponse",
    "DocumentListRequest",
    "DocumentListResponse",
    "DocumentChunkResponse",
    "DocumentProcessingRequest",
    "DocumentProcessingResponse",
    "DocumentStatsResponse",
    "DocumentGetRequest",
    "DocumentDeleteRequest",
    "DocumentDeleteResponse",
    "DocumentStatsRequest",
    "DocumentUploadRequest",
    "DocumentChunksResponse",
    # Health schemas
    "HealthCheckResponse",
    "DatabaseHealthCheck",
    "ReadinessCheckResponse",
    "LivenessCheckResponse",
    # Profile schemas
    "ProfileBase",
    "ProfileCreate",
    "ProfileUpdate",
    "ProfileResponse",
    "ProfileListRequest",
    "ProfileListResponse",
    "ProfileStatsResponse",
    "ProfileTestRequest",
    "ProfileTestResponse",
    "ProfileCloneRequest",
    "ProfileImportRequest",
    "ProfileExportResponse",
    "ProfileGetRequest",
    "ProfileDeleteRequest",
    "ProfileStatsRequest",
    "ProfileProvidersRequest",
    "ProfileDeleteResponse",
    "AvailableProvidersResponse",
    # Prompt schemas
    "PromptBase",
    "PromptCreate",
    "PromptUpdate",
    "PromptResponse",
    "PromptListRequest",
    "PromptListResponse",
    "PromptStatsResponse",
    "PromptTestRequest",
    "PromptTestResponse",
    "PromptCloneRequest",
    "PromptGetRequest",
    "PromptDeleteRequest",
    "PromptStatsRequest",
    "PromptDeleteResponse",
    # Analytics schemas
    "ConversationStatsResponse",
    "UsageMetricsResponse",
    "PerformanceMetricsResponse",
    "DocumentAnalyticsResponse",
    "PromptAnalyticsResponse",
    "ProfileAnalyticsResponse",
    "SystemAnalyticsResponse",
    "AnalyticsTimeRange",
    "AnalyticsExportRequest",
    "AnalyticsExportResponse",
    "DashboardResponse",
    "ConversationStatsRequest",
    "UsageMetricsRequest",
    "PerformanceMetricsRequest",
    "DocumentAnalyticsRequest",
    "SystemAnalyticsRequest",
    "DashboardRequest",
    "ToolServerAnalyticsRequest",
    # Tool server schemas
    "ToolServerBase",
    "ToolServerCreate",
    "ToolServerUpdate",
    "ToolServerResponse",
    "ToolServerStatusUpdate",
    "ServerToolBase",
    "ServerToolUpdate",
    "ServerToolResponse",
    "ToolUsageCreate",
    "ToolUsageResponse",
    "ToolServerMetrics",
    "ToolMetrics",
    "ToolServerAnalytics",
    "ToolServerHealthCheck",
    "BulkToolServerOperation",
    "BulkOperationResult",
    "ToolServerListRequest",
    "ToolServerDeleteResponse",
    "ToolServerOperationResponse",
    "ServerToolsRequest",
    "ServerToolsResponse",
    "ToolOperationResponse",
    # Events schemas
    "EventResponse",
    "ConnectionEstablishedEvent",
    "TestEventRequest",
    "TestEventResponse",
    "SSEStatsResponse",
    "AdminSSEStatsResponse",
    "BackupEvent",
    "JobEvent",
    "ToolServerEvent",
    "DocumentEvent",
    "SystemEvent",
    # Model Registry schemas
    "ProviderBase",
    "ProviderCreate",
    "ProviderUpdate",
    "Provider",
    "ModelDefBase",
    "ModelDefCreate",
    "ModelDefUpdate",
    "ModelDef",
    "ModelDefWithProvider",
    "EmbeddingSpaceBase",
    "EmbeddingSpaceCreate",
    "EmbeddingSpaceUpdate",
    "EmbeddingSpace",
    "EmbeddingSpaceWithModel",
    "ProviderList",
    "ModelDefList",
    "EmbeddingSpaceList",
    "DefaultProvider",
    "DefaultModel",
    "DefaultEmbeddingSpace",
    "ProviderDeleteResponse",
    "ProviderDefaultResponse",
    "ModelDeleteResponse",
    "ModelDefaultResponse",
    "EmbeddingSpaceDeleteResponse",
    "EmbeddingSpaceDefaultResponse",
]
