# coding: utf-8

"""
    Chatter API

    Advanced AI Chatbot Backend API Platform

    The version of the OpenAPI document: 0.1.0
    Contact: support@chatter.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class AgentInteractResponse(BaseModel):
    """
    Response schema for agent interaction.
    """ # noqa: E501
    agent_id: StrictStr = Field(description="Agent ID")
    response: StrictStr = Field(description="Agent response")
    conversation_id: StrictStr = Field(description="Conversation ID")
    tools_used: List[StrictStr] = Field(description="Tools used in response")
    confidence_score: Union[StrictFloat, StrictInt] = Field(description="Confidence score")
    response_time: Union[StrictFloat, StrictInt] = Field(description="Response time in seconds")
    timestamp: datetime = Field(description="Response timestamp")
    __properties: ClassVar[List[str]] = ["agent_id", "response", "conversation_id", "tools_used", "confidence_score", "response_time", "timestamp"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentInteractResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentInteractResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agent_id": obj.get("agent_id"),
            "response": obj.get("response"),
            "conversation_id": obj.get("conversation_id"),
            "tools_used": obj.get("tools_used"),
            "confidence_score": obj.get("confidence_score"),
            "response_time": obj.get("response_time"),
            "timestamp": obj.get("timestamp")
        })
        return _obj


