# coding: utf-8

"""
    Chatter API

    Advanced AI Chatbot Backend API Platform

    The version of the OpenAPI document: 0.1.0
    Contact: support@chatter.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class CacheStatusResponse(BaseModel):
    """
    Schema for cache status response.
    """ # noqa: E501
    cache_enabled: StrictBool = Field(description="Cache enabled status")
    cache_hits: StrictInt = Field(description="Cache hits")
    cache_misses: StrictInt = Field(description="Cache misses")
    cache_hit_rate: Union[StrictFloat, StrictInt] = Field(description="Cache hit rate")
    cached_items_count: StrictInt = Field(description="Number of cached items")
    cache_size_mb: Union[StrictFloat, StrictInt] = Field(description="Cache size in MB")
    last_cleared: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["cache_enabled", "cache_hits", "cache_misses", "cache_hit_rate", "cached_items_count", "cache_size_mb", "last_cleared"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CacheStatusResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
    mode='json',
        )
        # set to None if last_cleared (nullable) is None
        # and model_fields_set contains the field
        if self.last_cleared is None and "last_cleared" in self.model_fields_set:
            _dict['last_cleared'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CacheStatusResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cache_enabled": obj.get("cache_enabled"),
            "cache_hits": obj.get("cache_hits"),
            "cache_misses": obj.get("cache_misses"),
            "cache_hit_rate": obj.get("cache_hit_rate"),
            "cached_items_count": obj.get("cached_items_count"),
            "cache_size_mb": obj.get("cache_size_mb"),
            "last_cleared": obj.get("last_cleared")
        })
        return _obj


