
"""
    Chatter API

    Advanced AI Chatbot Backend API Platform

    The version of the OpenAPI document: 0.1.0
    Contact: support@chatter.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing import Self


class PromptCategory(str, Enum):
    """
    Enumeration for prompt categories.
    """

    """
    allowed enum values
    """
    GENERAL = 'general'
    CREATIVE = 'creative'
    ANALYTICAL = 'analytical'
    TECHNICAL = 'technical'
    EDUCATIONAL = 'educational'
    BUSINESS = 'business'
    CODING = 'coding'
    CUSTOM = 'custom'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PromptCategory from a JSON string"""
        return cls(json.loads(json_str))


