
"""
    Chatter API

    Advanced AI Chatbot Backend API Platform

    The version of the OpenAPI document: 0.1.0
    Contact: support@chatter.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
from enum import Enum

from typing import Self


class TestType(str, Enum):
    """
    Types of A/B tests.
    """

    """
    allowed enum values
    """
    PROMPT = "prompt"
    MODEL = "model"
    PARAMETER = "parameter"
    WORKFLOW = "workflow"
    TEMPLATE = "template"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TestType from a JSON string"""
        return cls(json.loads(json_str))


