"""
Chatter API

Advanced AI Chatbot Backend API Platform

The version of the OpenAPI document: 0.1.0
Contact: support@chatter.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Annotated, Any, ClassVar, Self

from chatter_sdk.models.o_auth_config_schema import OAuthConfigSchema
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictStr,
    field_validator,
)


class ToolServerUpdate(BaseModel):
    """
    Schema for updating a remote tool server.
    """  # noqa: E501

    display_name: (
        Annotated[str, Field(min_length=1, strict=True, max_length=200)]
        | None
    ) = None
    description: StrictStr | None = None
    base_url: (
        Annotated[
            str, Field(min_length=1, strict=True, max_length=2083)
        ]
        | None
    ) = None
    transport_type: Annotated[str, Field(strict=True)] | None = None
    oauth_config: OAuthConfigSchema | None = None
    headers: dict[str, StrictStr] | None = None
    timeout: Annotated[int, Field(le=300, strict=True, ge=5)] | None = (
        None
    )
    auto_start: StrictBool | None = None
    auto_update: StrictBool | None = None
    max_failures: (
        Annotated[int, Field(le=10, strict=True, ge=1)] | None
    ) = None
    __properties: ClassVar[list[str]] = [
        "display_name",
        "description",
        "base_url",
        "transport_type",
        "oauth_config",
        "headers",
        "timeout",
        "auto_start",
        "auto_update",
        "max_failures",
    ]

    @field_validator('transport_type')
    def transport_type_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(http|sse|stdio|websocket)$", value):
            raise ValueError(
                r"must validate the regular expression /^(http|sse|stdio|websocket)$/"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ToolServerUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set()

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of oauth_config
        if self.oauth_config:
            _dict['oauth_config'] = self.oauth_config.to_dict()
        # set to None if display_name (nullable) is None
        # and model_fields_set contains the field
        if (
            self.display_name is None
            and "display_name" in self.model_fields_set
        ):
            _dict['display_name'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if (
            self.description is None
            and "description" in self.model_fields_set
        ):
            _dict['description'] = None

        # set to None if base_url (nullable) is None
        # and model_fields_set contains the field
        if (
            self.base_url is None
            and "base_url" in self.model_fields_set
        ):
            _dict['base_url'] = None

        # set to None if transport_type (nullable) is None
        # and model_fields_set contains the field
        if (
            self.transport_type is None
            and "transport_type" in self.model_fields_set
        ):
            _dict['transport_type'] = None

        # set to None if oauth_config (nullable) is None
        # and model_fields_set contains the field
        if (
            self.oauth_config is None
            and "oauth_config" in self.model_fields_set
        ):
            _dict['oauth_config'] = None

        # set to None if headers (nullable) is None
        # and model_fields_set contains the field
        if self.headers is None and "headers" in self.model_fields_set:
            _dict['headers'] = None

        # set to None if timeout (nullable) is None
        # and model_fields_set contains the field
        if self.timeout is None and "timeout" in self.model_fields_set:
            _dict['timeout'] = None

        # set to None if auto_start (nullable) is None
        # and model_fields_set contains the field
        if (
            self.auto_start is None
            and "auto_start" in self.model_fields_set
        ):
            _dict['auto_start'] = None

        # set to None if auto_update (nullable) is None
        # and model_fields_set contains the field
        if (
            self.auto_update is None
            and "auto_update" in self.model_fields_set
        ):
            _dict['auto_update'] = None

        # set to None if max_failures (nullable) is None
        # and model_fields_set contains the field
        if (
            self.max_failures is None
            and "max_failures" in self.model_fields_set
        ):
            _dict['max_failures'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ToolServerUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "display_name": obj.get("display_name"),
                "description": obj.get("description"),
                "base_url": obj.get("base_url"),
                "transport_type": obj.get("transport_type"),
                "oauth_config": (
                    OAuthConfigSchema.from_dict(obj["oauth_config"])
                    if obj.get("oauth_config") is not None
                    else None
                ),
                "headers": obj.get("headers"),
                "timeout": obj.get("timeout"),
                "auto_start": obj.get("auto_start"),
                "auto_update": obj.get("auto_update"),
                "max_failures": obj.get("max_failures"),
            }
        )
        return _obj
